### ISSUE TITLE
Write a proposal for how provenance would be captured and expressed through the full workflow of DataArchive

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#1]
This proposal should include the following information by the end of the investigative work:

- [ ]  Data model 
- [ ] - Service architecture & its interaction with surrounding components
- [ ] - Assumptions and/or requirements on surrounding components
- [ ] - Prerequisites for development to start
- [ ] - ALL tasks needed to implement the component being proposed

**Comment by htpvu** [comment]
@emetsger the list of things I added above reflects what *I* need to get from the design. It may be beyond the scope of your current write up, in which case, I'd keep this ticket open until all of the information request can be provided, even if we need more than 1 doc or more than 1 meeting. 

Please let me know if you have any concern about what's being asked for.

**Comment by emetsger** [comment]
> Data model

An exploration of using W3C-Prov as a model is available (as of now, WIP) here:
https://docs.google.com/document/d/1qagU6LQE75mJR-zg86ujlkBL7iiMxYWKDpaWT-W-Jus/edit#

**Comment by htpvu** [comment]
@emetsger I updated the ticketdescription with checkboxes. please check things off as you make progress.

**Comment by emetsger** [comment]
> Data model

Brief exploration of the use of W3C Prov Collection
https://drive.google.com/open?id=132e0gZ9Z0o_kzf6lfvKI-LpqNogxJ1xE-E6PV2ki0CA

**Comment by emetsger** [comment]
> Data model

Formal data model [document](https://drive.google.com/open?id=1uubPouq6WVkAxpedTGDQIukcSBPTjrXwCODc_MCvYS8) up for review, which discusses not only the model but patterns that may apply for the creation and management of provenance

**Comment by htpvu** [comment]
DESCOPED
