### ISSUE TITLE
Brainstorming and categorizing events needed to be emitted/captured in JHU Data Archive

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#12]
The expected outcomes of this ticket are: 
- Not all inclusive list of major events (outcome from initial meeting)
- Data model for event (data type, etc)
- Serialization: JSON or what?

Some of the actions needed to execute the ticket include: 
- Schedule and lead a brainstorming meeting to create the list of major events type and capture the type of informational fields that should be associated with each events. 
- Prior to the meeting, have things for folks to response to: Elliot draw some pictures describing actors and components (pull together materials for meeting)
-- Who reads/write data
-- What information should be captured for each event

**Comment by emetsger** [comment]
Working document for events is here: https://drive.google.com/open?id=1AGgXOurIRzbrlOQHgB92thxGoyk0zcb9NJyviPaZp-U

**Comment by htpvu** [comment]
Meeting to ratify the proposed model and event took place on 10/18/19. 
We agreed to what was proposed and added 2 type of event: failure/error event and health check event. 

ticket can be closed when those two events are added to the documentation
