### ISSUE TITLE
investigate and produce diagram describing the cloud infrastructure for JHU Data archive

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#13]
Please put the output of this ticket in this document https://docs.google.com/document/d/1jaajDOi2Ryw7kIu5CuiWdtT2Bnzi-o1lJm_I333lHkI/edit

**Comment by jhujasonw** [comment]
Started talking with @derekbelrose about this.  There may be some gaps, but there is a preliminary draft in google docs.  Not sure yet if it's ready for review.  Will talk to him and see if we need to work on that doc some more.

**Comment by derekbelrose** [comment]
https://docs.google.com/document/d/1k4_IGu_f3p1TYJipvTxFOKDhTYU8GUJZOIZvEbPU3VM/view

In progress, but this has already been passed around to @htpvu and @jhujasonw

**Comment by jhujasonw** [comment]
This was reconciled with @derekbelrose  and @birkland and agreed upon at a previous meeting.  Closing this ticket as it was a blocker of others.
