### ISSUE TITLE
Investigate and propose approach to transfer files from Azure File Service mount to the final archival location

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#15]
The output of this ticket maybe of particular interest to @emetsger (current owner of Deposit Service)

**Comment by jgara** [comment]
_Assuming:_

1. VSM is on a Hopkins private network
2. Azure is on the public internet

connections initiated from Azure to VSM are not possible.

_One possible approach:_

An "Azure Download Service" (ADS) runs on the VSM system. The ADS polls an Azure queue for packages to download. If a package is available, the ADS can obtain from the queue (or some secure place accessible only to the ADS):

1. Azure storage account name (e.g. "derekazurestorage")
2. Azure Files "share name" (e.g. "uploadtest")
3. File path (e.g. "jeff/azcopy_test")
4. Package or File name(s)
5. SAS token
   a. [Example](https://stackoverflow.com/questions/53653473/generating-an-sas-token-in-java-to-download-a-file-in-an-azure-data-storage-cont) of obtaining SAS token programmatically in Java.

Using the "[azcopy](https://github.com/Azure/azure-storage-azcopy)" CLI utility and the above information, the ADS can download the package from Azure Files.

_Performance of azcopy:_

In my tests using a large (100GB) file, upload (VSM -> Azure) performance was > 100MB/s. Download (Azure -> VSM) speed was > 500MB/s.

_Alternative technologies_

1. Mounting the Azure Files share using SMB. In my testing, observed:
  a. slower speeds (typically 25MB/s)
  b. mount hangs
  c. instability: at one point, something went wrong and some files were copied to the SMB mount in an incomplete state. Waiting 12 hours did not clean them up. The only solution I found was running a PowerShell command (Close-AzStorageFileHandle).

**Comment by htpvu** [comment]
@jgara could you please put your findings into this document https://docs.google.com/document/d/1aXzISpcD4M-1GRIyBVW9-RBreWxWFO1P0f5RqmEHaR4/edit ?

Once it's there, we can ask the other system engineers to review and raise any concerns. If all is good, then we'll document the decision and this document could serve as documentation for the future. 

Let me know if you have questions.

**Comment by htpvu** [comment]
Done and parked.
