### ISSUE TITLE
Investigate and decide on containerization strategy

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#16]
Looking into kubernetes to break up docker containers into two different places to see if we can take advantage of image binding.

part of ticket #13

**Comment by derekbelrose** [comment]
As @jhujasonw is the architect for this project, I imagine that the final decision will fall on him based on recommendations that I have as well as findings from the research.  I am bringing him in as an Assignee for this Issue.

**Comment by derekbelrose** [comment]
Findings so far:

We really only have one Containerization solution and that's Docker. The other containerization options do not seem to have a central hub and require us to host some form of software to host images.

While that's possible, there's little reason not to use Docker Hub for hosting images as long as they don't have to be private.  Once they are private we might have to use one of the private cloud Registries such as ECR (AWS Elastic Container Registry) and Azure Container Registry.

For container orchestration, there's Azure Containers, AWS ECS, Docker Swarm, Kubernetes, Rancher, etc.

Seeing as this is run in Azure and we can't use ECS (which I already have deep working knowledge of), the two remaining choices are new to the team.  Azure Containers is an API driven wrapper around, we think, Kubernetes. As we have to learn a new technology, my opinion is that we learn a cloud agnostic technology that can be applied to all Library projects moving forward.

Kubernetes has been unofficially selected as the way IT does container orchestration now. It can run anywhere and uses Docker as a containerization.  It also works with containerd and rckt which might, albeit unlikely, need to be researched in the future if Docker, Inc doesn't make it as a company.

My opinion at this point in the research is that we use Kubernetes + Docker.  I have been working with it for a couple weeks now.  It's complex but stable and has a lot of functionality.

**Comment by derekbelrose** [comment]
My reason for the "Docker, Inc. doesn't make it as a company" comment:
https://www.zdnet.com/article/docker-is-in-deep-trouble/

If Docker, Inc doesn't make it as a company, Docker Hub will be affected and we'll need somewhere to put our images. That could be a private registry either hosted in the Cloud or self-hosted.

**Comment by htpvu** [comment]
@derekbelrose what is the state of this ticket at this point?

**Comment by derekbelrose** [comment]
The decision was made to go with Kubernetes as scheduler/orchestration with Docker as the container engine.
