### ISSUE TITLE
Create archive-docker env to enable development in similar manner to that of PASS

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#22]

**Comment by emetsger** [comment]
Using https://github.com/emetsger/slarx-docker as a test, I was able to compose an image for Fedora, and have the Docker Cloud environment automatically build, test, and push the image.

At this point I just need to review any outstanding requirements for the image and then move the repository to the appropriate location.

**Comment by emetsger** [comment]
You have to 1) Connect your Docker repository to a GitHub repository. 2) Flip on “Automated Builds” on the Docker Cloud side.  3) Configure the location of the build context and Dockerfile relative to the GitHub repository root.  4) Finally, add a docker-compose.test.yml in the configured build context directory with the sut service defined.
It looks like fundamentally there can only be one image produced per GitHub repository.

**Comment by emetsger** [comment]
Deposit Services leverages dependent builds, which is implemented in a hacky way, which would need to be revisited in this approach.
