### ISSUE TITLE
Investigate using relative URIs in the indexer (1 Day LE) 

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#23]

**Comment by birkland** [comment]
See: https://docs.google.com/document/d/1ynNYuiukEzc-rH-JoIDwXTF02jeYTu_gmZcXRcKHOsA/edit?pli=1

Outcome is that the infrastructure will be updated so that backend and frontend use the _same_ URIs, so no changes are needed to the indexer
