### ISSUE TITLE
Investigate and propose an approach for supporting HTTP File Upload for the data Archive

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#7]
As part of this ticket's work, please shepherd the proposal through the ratification phase and document team's decision on the same doc:
https://docs.google.com/document/d/1h_BquSJ4LpCNWYoJ9KETXCG9WFD2k7Oo2-KPmRX8rYA/edit#

**Comment by birkland** [comment]
Blocked by decision on storage for the archive (oneDrive vs azure files), but conclusions so far have been added to the doc.
