### ISSUE TITLE
Investigate whether simple ElasticSearch would work for the data archive

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-general-issues#8]
the work for this ticket depends on:
- the understanding of UI use cases: what queries would be used, is flat JSON-LD being put into UI
- The understanding of provenance and surrounding use cases

**Comment by birkland** [comment]
Still blocked by understanding the provenance paradigm and use cases

**Comment by birkland** [comment]
Based on recent understanding of the evolving MVP, a pass-style indexer and elasticsearch will work, and is necessary.
